"""keywords

Revision ID: b1003d0065a5
Revises: e36d919d0e93
Create Date: 2019-10-31 20:43:02.362352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1003d0065a5'
down_revision = 'e36d919d0e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(length=128), nullable=True))
    op.add_column('posts', sa.Column('keywords', sa.String(length=64), nullable=True))
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', mysql.TEXT(), nullable=True))
    op.drop_column('posts', 'keywords')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
